# Change these first
owner: Roco-Team # Your GitHub organization or username, where this repository lives
repo: stats # The name of this repository

sites:  
  - name: Archives (archived.roco.work) 
    url: https://archived.roco.work/
    
  - name: URL Redirection (roco2.tk) 
    url: https://roco2.tk/
    
  - name: Images (img.roco.work)
    url: https://img.roco.work/hei.jpg
    
  - name: Navigation Page (w.roco.ml)
    url: http://w.roco.ml/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.rocoawa.com
  # baseUrl: /your-repo-name
  logoUrl: https://roco.work/img/logo.png
  name: Status / Roco - Team
  introTitle: "This is a status page from **Roco - Team**."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Github
      href: https://github.com/Roco-Team
    - title: Contact
      href: mailto:co@rocoawa.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration 
