# Change these first
owner: Roco-Team # Your GitHub organization or username, where this repository lives
repo: stats # The name of this repository

sites:
  - name: Profile Page (roco.work)
    url: https://roco.work/r.png

  - name: Roco - Team (rocoawa.com)
    url: https://rocoawa.com/
    
  - name: Archives (archived.roco.work) 
    url: https://archived.roco.work/
    
  - name: Blog (blog.roco.work)
    url: https://blog.roco.work/archives/11/
    
  - name: Images (img.roco.work) 
    url: https://img.roco.work/IMG_4010.jpg
    
  - name: URL Redirection (roco2.tk) 
    url: https://roco2.tk/
    
  - name: Team announcements (announce.rocoawa.com) 
    url: https://announce.rocoawa.com/
    
  - name: Navigation Page (w.roco.ml)
    url: http://w.roco.ml/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.rocoawa.com
  # baseUrl: /your-repo-name
  logoUrl: https://roco.work/img/logo.png
  name: Status / Roco - Team
  introTitle: "This is a status page from **Roco - Team**."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Main-site
      href: https://status.roco.work
    - title: Contact
      href: mailto:co@rocoawa.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
